# -*- coding: utf-8 -*-
"""code80.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbX-pqDpBSd_xwdhMDs_KFWoOKA4VjN5
"""

!pip install prettytable

from prettytable import PrettyTable

receipt = PrettyTable()
receipt.field_names = ['№','Продукт','Цена','Количество','Стоимость']

print(receipt)